application: staticfile
version: 1
runtime: go
api_version: 3

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /index\.html
  static_files: index.html
  upload: index.html

- url: /.*
  script: _go_app