application: ghostnotest
version: 8
runtime: go
api_version: 3

handlers:
- url: /required
  script: _go_app
  login: required

- url: /admin
  script: _go_app
  login: admin

- url: /.*
  script: _go_app